id: AB5D57E16
title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
type: translation
pechas:
- I229766BC
- I488D9689
- I044DD4D2
- I43B4B163
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:10:33.579633
  last_modified_at: 2023-01-04 13:10:33.579637
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I229766BC/96CB: 474A
  I488D9689/A0A7: 474A
  I044DD4D2/DAFA: 474A
  I43B4B163/2DCA: 474A
